version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rolup
    ports:
      - "5432:5432"
    volumes:
      - ../ddbb/postgres:/var/lib/postgresql/data